# https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates
version: 2
updates:
  # Laravel Backend - Composer dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "07:00"
      timezone: "Asia/Tokyo"
    assignees:
      - su3-hokkaido
    open-pull-requests-limit: 99

  # Vue.js Frontend - npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "07:00"
      timezone: "Asia/Tokyo"
    assignees:
      - su3-hokkaido
    open-pull-requests-limit: 99
